### ISSUE TITLE
I have a PipeInvokeFailedException

### ISSUE THREAD

**Issue by abaudouin84** [gerardo-lijs/CrystalReportsRunner#13]
Hi,

On a project, I have this exception :
PipeMethodCalls.PipeInvokeFailedException : 'System.IndexOutOfRangeException: Could not find column 2.

The report has been created with CR SP34.

I join a little project to reproduce.

[TestReport.zip](https://github.com/gerardo-lijs/CrystalReportsRunner/files/13378335/TestReport.zip)

**Comment by abaudouin84** [comment]
yes I finally found the problem. It's because I used a dataset from a XSD designer and and I guess this causes problems with JSON serialization because it's not a base Dataset. So I have created a converter and it's working now !

**Comment by abaudouin84** [comment]
Thank you for your great job with this project ! You have no idea how much you are helping me.

**Comment by gerardo-lijs** [comment]
Glad it helped!! The main reason we shared this is to help others. Serialization of Datasets can be improved indeed. I will take a  look at your code and see if I can improve it for this case. There are some simple unit tests to try this isolated from named pipes that will help.
