### ISSUE TITLE
print to printer

### ISSUE THREAD

**Issue by AymanPhysics** [gerardo-lijs/CrystalReportsRunner#17]
Dear Gerardo, thanks a lot for you solution
but I COULDN'T FIND print to printer
it's very important to print receipts directly without opening the preview
thanks a lot
I cannot wait for your response

**Comment by gerardo-lijs** [comment]
Hi, this is something that can be added to the library. It will work very similar to the Export method, but instead Printing. Do you want to give it a try and see if you can make the copy/paste of this methods in a PR?

**Comment by gerardo-lijs** [comment]
I ended up doing it as it looked so simple. Please check the PR https://github.com/gerardo-lijs/CrystalReportsRunner/pull/18

You can run the branch locally and try with the WpfCaller sample app if this works for you. It's basically printing to default printer with this options.

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/1da9e710-f9f0-4b15-9126-d073844aa37f)

```
document.PrintToPrinter(nCopies: 1, collated: false, startPageN: 0, endPageN: 0);
```

If you need other options to send to the PrintToPrinter Crystal Reports method, it can be done, by sending the parameters in the methods and adjusting the interfaces. Please let me know and I will create release after that.

**Comment by AymanPhysics** [comment]
thanks a lot

**Comment by gerardo-lijs** [comment]
Did it work for you? Can I close/merge this?

**Comment by AymanPhysics** [comment]
Thanks for your following
But actually, I have understood the pipeline concept from your code,
And did my own pipeline to my exists code

So, thanks a lot 🙏🙏

Sent from my iPhone

On 28 Feb 2024, at 5:33 PM, Gerardo Lijs ***@***.***> wrote:

﻿

Did it work for you? Can I close/merge this?
