### ISSUE TITLE
List Of Parameters

### ISSUE THREAD

**Issue by Powerguim** [gerardo-lijs/CrystalReportsRunner#20]
Hi, 
I cannot in no way send a list of parameters to the report.
In my report i accept a list of numbers, and in dotnet Framework in my other project i would send a array of ints, and work just fine.

Now in here if i just send a number all works fine, if i send a list, array gives an error the values do not match, i've tried everything

**Comment by gerardo-lijs** [comment]
Hi, I will create another Unit Test for array/list input parameters. It's very possible your are doing nothing wrong and this use case was not considered in the serialization as it was not tested. I will run some tests and let you know.

**Comment by Powerguim** [comment]
Thank you very mutch

**Comment by gerardo-lijs** [comment]
I can confirm it was indeed that the lib does not handle list of parameters. I already have a working code for this and will publish later on. Just wanted to let you know its fixed.
