### ISSUE TITLE
Problem while publishing with PublishSingleFile parameter

### ISSUE THREAD

**Issue by Kitsunejasutin** [gerardo-lijs/CrystalReportsRunner#22]
I currently publishing a application with the following parameters

`dotnet publish -c Release --self-contained true -r win-x64 -p:PublishSingleFile=true  -p:EnableCompressionInSingleFile=true -o %~dp0publish`

An error pop-ups whenever the program calls the Runner

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/73803767/2f83a50e-5599-455f-869b-f019b9391290)

I inspected the code behind and it might be missing dependencies or file while doing `PublishSingleFile`

For more information about the file structure on publish:

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/73803767/f1eea24d-0f4b-4771-bf86-bbbfae83e7c3)

CrystalReportRunner Folder contents:
![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/73803767/db4c351f-0f84-4940-bbb3-5ac2ce33c9ed)

Tested wIthout any `PublishSingleFile` parameter and it works fine.

**Comment by Kitsunejasutin** [comment]
With some meddling with some parameters regarding `PublishSingleFile` I stumbled upon `IncludeNativeLibrariesForSelfExtract` parameter.

Info: https://learn.microsoft.com/en-us/dotnet/core/deploying/single-file/overview?tabs=cli#native-libraries

With the new dotnet command `dotnet publish -c Release --self-contained true -r win-x64 -p:PublishSingleFile=true -p:EnableCompressionInSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -o %~dp0publish` It works perfectly well now. I will wait for Mr. Gerardo insights about this.

**Comment by gerardo-lijs** [comment]
Hi, very glad you manage to get it working with single file publishing! I don't have real production experience with publishing single file apps (apart from testing them in some small sample projects) so there is not much insight I can provide on this topic.

Is there any change needed in the library/nuget so your app can use it with single publish? If so, please let me know or send a PR so we can add it. Another option if no changes are needed and you want to contribute, feel free to drop a PR adding this in the README file for other people who might run into this issue.

**Comment by Kitsunejasutin** [comment]
This is literally outside of the scope of this issue, but I want to ask if slow down on first load is a thing? I noticed that on my dev machine, the window and report loads fast but right after I transfer it on the client machine that is on a Active Directory Domain, startup of the report takes longer than normal. After the first load, other report loads fine.

**Comment by gerardo-lijs** [comment]
Hi, are you using the signed versión of the ReportRunner.exe or you are deploying your own foro? In some cases, Windows Defender takes longer to check executables the first time they run,  that might also explain why it takes time the first time, and once the Runner is loaded, communication via NamedPipes is very fast.

**Comment by Kitsunejasutin** [comment]
> Hi, are you using the signed versión of the ReportRunner.exe or you are deploying your own fork? In some cases, Windows Defender takes longer to check executables the first time they run, that might also explain why it takes time the first time, and once the Runner is loaded, communication via NamedPipes is very fast.

Currently using the one from Nuget Package
