### ISSUE TITLE
Issue in pdf

### ISSUE THREAD

**Issue by rozyjaret** [gerardo-lijs/CrystalReportsRunner#25]
Hi,
I am running the sample project - WpfCaller. When I an clicking on Export Report , I can see the report , but instead of UserName , I can see a number. Issue is with the string type parameters only.

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/16833769/172eda7b-1235-4e01-9283-4c1b996e05e3)
![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/16833769/7493d2b3-6f14-490e-a6f6-ab45162843db)

**Comment by gerardo-lijs** [comment]
Thanks for reporting this. Found the bug that was introduced a few commits ago. Will fix and release version 1.4.2. The bug is here FYI

![image](https://github.com/gerardo-lijs/CrystalReportsRunner/assets/14139570/6baac139-b7f4-446c-9d39-4a273152e217)

**Comment by rozyjaret** [comment]
Thanks for the feedback!
