### ISSUE TITLE
Export to stream any Excel Format

### ISSUE THREAD

**Issue by seang96** [gerardo-lijs/CrystalReportsRunner#32]
To be clear I am experiencing this with a custom runner (different version of crystal). I am using 13.0.31.

I get a System.IO.FileNotFound exception on [L106 of the engine](https://github.com/gerardo-lijs/CrystalReportsRunner/blob/90b592f85798f54cfbdc41a5cfb4fbcc0a121cdc/src/LijsDev.CrystalReportsRunner.Core/CrystalReportsEngine.cs#L106) whenever I use Excel formats. I haven't tried any other but PDF, and PDF works with the stream export. The file export works with the spreadsheets.

**Comment by gerardo-lijs** [comment]
I'm not sure what can be causing this. L106 in the Engine is a MemoryMappedFile, which is how the runner shares the stream/data with caller/main app. It might not be executing correctly. Does this also happen is you test in one of the default runners version 34 for example? Can you provide a test repository for me to run/debug?

**Comment by seang96** [comment]
I added a PR with my additions for 13.0.31 runner so we can get that officially supported in your repo and investigate this issue further. Since we require everything to run on 13.0.31 at my organization, testing on other versions would be a little more difficult.

Thanks for this project, it is some great work!

**Comment by seang96** [comment]
I believe I figured this issue out kind of. It was somewhat related to another issue I was having where I was using the wrong provider for my reports by using the built in factory methods. I believe the provider MSOLEDBSQL doesn't support excel exports through the export to stream,  however the provider I traditionally use works fine, SQLOLEDB.

**Comment by gerardo-lijs** [comment]
Glad you manage to get it fixed! Providers are difficult. Right now I'm using MSOLEDBSQL19 so that it can work with Microsoft SQL Server 2022 and it's enforced encryption, but for every app it can be different based on your needs/legacy inheritance. That's why I tried to leave this completely open for customization, so you can use whatever you want. One user was even using it to connect with MySQL
