### ISSUE TITLE
Getting error Operation illegal on linked parameter.

### ISSUE THREAD

**Issue by pengaidev** [gerardo-lijs/CrystalReportsRunner#35]
Getting error message while trying to add parameter to crystal report the parameter.
This issue when I have sub report and linked parameter to the sub report.

`report.Parameters.Add("ShowGroupItemLine", true);`

After added this line of code and running the thrown an exception:
Operation illegal on linked parameter.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)

**Comment by gerardo-lijs** [comment]
Hi, please check this PR https://github.com/gerardo-lijs/CrystalReportsRunner/pull/11 that I never got to test and merge, but it was related to linked parameters and the solution. That user was able to use linked parameters with those changes. I will need to review and merge that PR to provide support for linked parameters, but I never used linked parameters in Crystal Reports so before I do it I wanted to make sure the solution really works and it does not break current implementation.

**Comment by pengaidev** [comment]
Thank you for your help, I have found another solution that doesn't break any change of your library, The solution is rename the sub report that linked with parent report to the difference name to make it work.
