### ISSUE TITLE
Cannot find LijsDev.CrystalReportsRunner.Shell on Nuget

### ISSUE THREAD

**Issue by Magellus** [gerardo-lijs/CrystalReportsRunner#37]
I need to make a custom Runner for my runtime version of Crystal.
I am following your guide to do so.
But it seem that I cannot import LijsDev.CrystalReportsRunner.Shell from Nuget.
I tried LijsDev.CrystalReportsRunner.Core believing it could have changedneme in 2 years, but it did not work.

Any pointer on this would be gladly appreciated.

Thank for your time.

**Comment by Magellus** [comment]
I am blind.

**Comment by Magellus** [comment]
First of all, A big thank for theses library. They are life saver.

Second I fail to rebuild Shell and and Core. 
It seems that I need to have Git installed on my computer. 
Which I don't need for now. (When our migration job is done we'll get to it)
Do I really need MinVer in my dependancies?

**Comment by Magellus** [comment]
Also, the path to VierwerForm, ReportsUtils and MemoryMappedFileUtils in
https://github.com/gerardo-lijs/CrystalReportsRunner/blob/main/docs/custom-runner.md
need to be corrected to point in the Shared folder.

**Comment by gerardo-lijs** [comment]
Hi, you don't need to have MinVer if you fork the project and create your own runner/lib. We use that for keeping versioning in the dlls and nuget we release. Thanks for pointing out the paths are not using the shared folder. We made that change later on to have several versions with the same shared code.

It might help yo publish a sample runner which does not depend on any of this, neither MinVer, nor shared folders, and have the guide use that as an example.

Let me know if any doubt!

**Comment by Magellus** [comment]
Good morning Gerardo!
Thank again for that great project.
After a few mess around and a lot of reading and try and error, I finally manage to make it work for my crystal runtime 13.0.0.9.
The learning curve was a little bit steep for me, but I made it! :)

I needed to modify slightly the core the shell and the runner to add some property requiered in our production system.

Tho, now, I would like to know if there is a way to get back some info from the runner? liLe the number of page printed and other stuff like that.
We use that ReportDocument function "CrReportDocument.FormatEngine.GetLastPageNumber()"
I am not quite sure if the shell or the core could send back info from the runner. Or if I need to create a new pipe to get information back from it. The concept of pipe is fairly new to me.

Thank for any help or pointer in the right direction.

**Comment by gerardo-lijs** [comment]
Hi, glad to hear you made it work!! It's possible to get information from the report. You will need to create new methods for it. Probably modify the ShowReport so that it return an object with all the information you want to collect. Named pipes is tricky, but one of the best ways to "talk" between two different processes. You can also create a new pipeline that can run in parallel too. There are really lots of options...depending what you need and how you will like the API to work.
