### ISSUE TITLE
Creating your own Runner

### ISSUE THREAD

**Issue by dpmangwiro** [gerardo-lijs/CrystalReportsRunner#6]
I have somehow failed to follow through the instructions. The links provided do not go anywhere. I am not sure how to link depencies to Shell and Runner Core, so i have errors everywhere.

**Comment by gerardo-lijs** [comment]
Hi, creating your own runner is quite complex. The instructions @mhmd-azeez wrote are very detailed but you can also try cloning the project and start from a working runner and make the changes you need instead of starting from scratch. Why are you trying to create your own runner?

**Comment by dpmangwiro** [comment]
I'm not as well experienced and just wanted the easiest way. Now you have pointed it out to me clearly. I will try cloning, it i face difficulties then I will have to just upgrade the installed version to crystal 32. Many thanks.
