### ISSUE TITLE
in ASP.net 6 MVC app it run on localpc and open the crystal report but when it hosted in local IIS it wont work.

### ISSUE THREAD

**Issue by skasad21** [gerardo-lijs/CrystalReportsRunner#8]

**Comment by mhmd-azeez** [comment]
Hello @skasad21 can you provide any details why it won't work? An error message would be great

**Comment by skasad21** [comment]
Actually I am kind of noob so. Let me explain what i did. I download the sample project you give the i add a .net core MVC project. 
Then Add a button on view page and in controller i add a method. In side the method i actually did nothing new just copy all the code from sample console app. only edit i did was copy dataset and report file in a seperate folder and add then in the method. So, it dont give me any error work great but when i hosted it in my local IIS then it wont work. i mean no crystal report open. 

Controller code :
public async void ShowReportAsync()
{
     string webRootPath = _env.WebRootPath;
     await reportClass.testreportAsync(webRootPath);
} 

Method:

        public static async Task testreportAsync(string webRootPath)
        {
            try
            {
                // ========== Initializing Engine ===========

                // Method 1: With Connection string
                using var engine = new CrystalReportsEngine();

                // Method 2: Without Connection string
                // using var engine = new CrystalReportsEngine();

                // ========== Customizing Viewer Settings ===========

                engine.ViewerSettings.AllowedExportFormats =
                    ReportViewerExportFormats.PdfFormat |
                    ReportViewerExportFormats.ExcelFormat |
                    ReportViewerExportFormats.CsvFormat |
                    ReportViewerExportFormats.WordFormat |
                    ReportViewerExportFormats.XmlFormat |
                    ReportViewerExportFormats.RtfFormat |
                    ReportViewerExportFormats.ExcelRecordFormat |
                    ReportViewerExportFormats.EditableRtfFormat |
                    ReportViewerExportFormats.XLSXFormat |
                    ReportViewerExportFormats.XmlFormat;

                engine.ViewerSettings.ShowRefreshButton = false;
                engine.ViewerSettings.ShowCopyButton = false;
                engine.ViewerSettings.ShowGroupTreeButton = false;
                engine.ViewerSettings.ShowParameterPanelButton = false;
                engine.ViewerSettings.EnableDrillDown = false;
                engine.ViewerSettings.ToolPanelView = ReportViewerToolPanelViewType.None;
                engine.ViewerSettings.ShowCloseButton = false;
                engine.ViewerSettings.EnableRefresh = false;               


                engine.ViewerSettings.SetUICulture(Thread.CurrentThread.CurrentUICulture);

                // ========== Showing the Report ===========
                var dataset = new PersonDataset();

                var personsTable = dataset.Tables["Persons"];

                for (int i = 0; i < 100; i++)
                {
                    var row = personsTable!.NewRow();
                    row["Name"] = $"Person {i + 1}";
                    personsTable.Rows.Add(row);
                }


                // Method 1: Full Control
                // string test = _hostingEnvironment.WebRootPath;
                string test = webRootPath + @"\sReport\DatasetReport.rpt";
                var report = new Report(test, "Sample Report")
                {
                    DataSets = new List<System.Data.DataSet> { dataset }
                };
                report.Parameters.Add("ComputerName", Environment.MachineName);

 
                await engine.ShowReport(report);
                Console.ReadKey();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }           
            

        }
        
        Thanks for the reply.

**Comment by mhmd-azeez** [comment]
@skasad21 can you please upload the Runner logs here? By default it's in `ProgramData/LijsDev/CrystalReportRunner/logs`. But you can also specify it through setting `engine.LogDirectory`

**Comment by skasad21** [comment]
What I did is:
Add This line 
**engine.LogDirectory = @"C:\ProgramData\LijsDev\CrystalReportRunner\logs";**
After 
await engine.ShowReport(report);
That line
 When i run locally it dont create any log file
 
Also after publishing again in Local IIS it dont create any log file

Let me know if i make any mistake. And also how can i share full code with you?

**Comment by mhmd-azeez** [comment]
Yeah, that'd be helpful. But I am not sure if the Runner works for ASP.NET MVC

**Comment by skasad21** [comment]
How can i share the code with you ? In project it work well but if hosted in Local IIS it won't work. Let me know how can i share the code with yo.

**Comment by mhmd-azeez** [comment]
if it's okay, please zip it (remove the bin/obj folder first plesae) and upload it here

**Comment by skasad21** [comment]
[CrystalReportsRunnertest.zip](https://github.com/gerardo-lijs/CrystalReportsRunner/files/10851834/CrystalReportsRunnertest.zip)

**Comment by skasad21** [comment]
Sorry for late reply in my previous comments you will get the files. I deleted bin/obj folder

**Comment by Rog4ner** [comment]
I web apps, I think it's a better idea to export the report in PDF format and show it in a route of your web app, instead of using the method engine.ShowReport you can use the engine.Export method. Or this is not an option?

**Comment by gerardo-lijs** [comment]
Agree with @Rog4ner . In web applications you usually export to PDF. The runners show methods/UI are meant for desktop apps and use the Crystal Reports Viewer for WPF, they won't work in the web.

**Comment by skasad21** [comment]
I thought it will work on .net 6 MVC project.

**Comment by mhmd-azeez** [comment]
@skasad21 does `engine.Export` work? Because even if `ShowReport` works, it provides no value for web apps since your users can't see what's on your server

**Comment by skasad21** [comment]
Sorry for really late reply. One interesting things i saw when i click on the show button i saw "LijsDev Crystal Reports Runner" process start but can't find the report file when i am hosting my site on Local IIS. but when i running from my project solution it work perfectly.

**Comment by Gildedter** [comment]
Glad I found this, I'm doing the same thing as he was, but I'm on .NET MVC 8.0, I have my own test report ([Report1.zip](https://github.com/user-attachments/files/17288303/Report1.zip)) to see if this solution works, I tried exporting it as a stream as seen here:
![image](https://github.com/user-attachments/assets/d988b143-52e3-4779-9c0a-0254e47bb650)

but upon deployment (both IIS EXpress and regular http) I'm getting several errors
